name: Cron Bump Commits

on:
  schedule:
    - cron:  '* */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci

    - name: Update commit hashes
      run: node update.js

    - name: Commit files
      run: |
        git config --local user.email "matthew.peveler@gmail.com"
        git config --local user.name "MasterOdinBot"
        git commit -s -m "Update commit hashes" -a || :

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
